name: darb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^2.0.0
  dio: ^5.11.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # تفعيل مجلد الخطوط كملفات أصول العامة
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/logo.svg
    - assets/images/logo.png

  # تعريف عائلة الخط وربط الملفات بحسب الأوزان
  fonts:
    - family: Noto Sans Arabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700