// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUWGKpWqd_zjPFrAmvMCpo8KxzTQgi-v4',
    appId: '1:675747972996:web:4705ef723f1eecfc1c7fd1',
    messagingSenderId: '675747972996',
    projectId: 'darrb-app',
    authDomain: 'darrb-app.firebaseapp.com',
    storageBucket: 'darrb-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtGhr-e6fuAYN4UfZteVt0-QNoeaedUnU',
    appId: '1:675747972996:android:6e1aa7202f4ff63f1c7fd1',
    messagingSenderId: '675747972996',
    projectId: 'darrb-app',
    storageBucket: 'darrb-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwWRWfcodZLoWzF9iTsfDeE1kr5bVa8A',
    appId: '1:675747972996:ios:d33c8618d6d747a71c7fd1',
    messagingSenderId: '675747972996',
    projectId: 'darrb-app',
    storageBucket: 'darrb-app.firebasestorage.app',
    iosBundleId: 'com.example.darb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUWGKpWqd_zjPFrAmvMCpo8KxzTQgi-v4',
    appId: '1:675747972996:web:92dba421bef668c41c7fd1',
    messagingSenderId: '675747972996',
    projectId: 'darrb-app',
    authDomain: 'darrb-app.firebaseapp.com',
    storageBucket: 'darrb-app.firebasestorage.app',
  );
}
